### ISSUE TITLE
Coc-angular doesn't work if installed thorough package manager

### ISSUE THREAD

**Issue by EJIqpEP** [iamcco/coc-angular#12]
Hi there. Thanks a lot for the great plugin!
I'm trying to install coc-angular through Plug to lock all packages and not "automagically" through coc itself.
```
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}
Plug 'iamcco/coc-angular', {'do': 'yarn install --frozen-lockfile'}
```
It is installed fine and I can see coc-angular in the list of `CocList extensions`.  However it is not started when I open angular template and it looks like it's completely not installed.

As the moment when I write `CocInstall coc-angular` everything started to work just fine.
Any ideas what am I doing wrong? All other coc-plugins are working fine with this approach.

**Comment by iamcco** [comment]
Use `Plug 'iamcco/coc-angular', {'do': 'yarn install --frozen-lockfile && yarn build'}`
