### ISSUE TITLE
Completion cursor placement not behaving as expected

### ISSUE THREAD

**Issue by ayazhafiz** [iamcco/coc-angular#14]
I have been unable to reproduce the expected cursor completion behavior implemented at

https://github.com/iamcco/coc-angular/blob/770db6f65f411a6ae17e9ed2b9acd14ded56d683/src/middleware/provideCompletionItem.ts#L59-L78

For example, completing `click` in the following template

```
<div (clic|)></div>
```

Currently gives

```
<div (click=""|)></div>
```

on my machine, with only coc and coc-angular enabled as packages.

Could anyone else verify that they are experiencing the same behavior? If this is in fact not the expected behavior, I would be happy to submit a patch for this.

**Comment by iamcco** [comment]
I can reproduce the issue. it only works as expected that type start with `(`.

**Comment by iamcco** [comment]
The easy way to test local extension is to add the extension directory to vim's `runtimepath`, coc will auto load extension from `runtimepath`.
