### ISSUE TITLE
Access object in htlm file

### ISSUE THREAD

**Issue by nxvu699134** [iamcco/coc-angular#16]
# Screenshot

![image](https://user-images.githubusercontent.com/27850048/77998752-c3a7e580-735b-11ea-940f-f088dba20f59.png)

- If I get attribute like in image, lsp alway mark it an error, but when I change to `col['col_id']` that error was not happen

- My environment
 ```
Angular CLI: 9.0.6
Node: 12.16.1
OS: linux x64
```

Any idea to fix that ?

Thanks

**Comment by iamcco** [comment]
No idea. It works for me, check your type of freezeColumns.

**Comment by nxvu699134** [comment]
type of `col` is an object with some atts and it contain `col_id`. `freezeColumns` is an array of object
```
  freezeColumns: object[] = [
    { header_id: 'blabla', col_id: 'id'},
    { header_id: 'blabla1', col_id: 'id1'},
  ];
```

**Comment by iamcco** [comment]
So it's expected.
