### ISSUE TITLE
coc-angular attribute completion doesn't include square brackets and parenthesis

### ISSUE THREAD

**Issue by skromez** [iamcco/coc-angular#20]
**Describe the bug**
Angular attribute completion doesn't include square brackets and parenthesis

And I'm also using coc-snippets, could that be an issue? 

**To Reproduce**
1. Create a simple `<p>` tag
2. Start typing ng to trigger ngModel completion
4. See that there is no variants with two-binding completion for ngModel

**Expected behavior**
Should look like on the screenshot on the main page of this Github page

**Screenshots**
[screenshot](https://i.imgur.com/uXZq7Bi.png)
 - OS: Linux

What could be the issue?

**Comment by iamcco** [comment]
It's expected. You should type `(` `*` `[`. Take a look at https://github.com/angular/vscode-ng-language-service/issues/302
