### ISSUE TITLE
Unable to load schema from '/NODE_PATH/@angular/cli/lib/config/schema.json' :CocDiagnostics

### ISSUE THREAD

**Issue by danushk** [iamcco/coc-angular#22]
Should be issue with your coc-angular extension

_Originally posted by @chemzqm in https://github.com/neoclide/coc.nvim/issues/2795#issuecomment-754065590_

**Describe the bug**
here is the bug 
![image](https://user-images.githubusercontent.com/185419/103558986-76086c80-4edb-11eb-8b84-eb265823f7a3.png)

**To Reproduce**
1 move node_modules folder to a common place outside your project directory
2 set NODE_PATH env variable to that on your .bashrc
3 open an existing angular project on vim enabled with Coc
4 run :CocDiagnostics

**Expected behavior**
i should not see this warning 

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by iamcco** [comment]
I don't think it's from coc-angular, disable coc-json then ti check it again.

**Comment by chemzqm** [comment]
Looks like issue with specific angular.json, can't reproduce.
