### ISSUE TITLE
GoToDefinition

### ISSUE THREAD

**Issue by andy-dev** [iamcco/coc-angular#23]
**Describe the bug**
Hello. I believe I might just be missing one more step. I added coc-angular. When I am in a HTML file and my cursor is over a component. If I try to go to definition (vimrc: nmap <leader>gd <Plug>(coc-definition)) I does not navigate to the definition.

**Comment by iamcco** [comment]
make sure extension is activated

**Comment by shyallegro** [comment]
had the same issue, to solve it I had to run `:set filetype=html`
looks like polyglot or some other plugin sets the filetype to htmldjango not sure how to force *.html files to set filetype to html
