### ISSUE TITLE
Directive error in the angular template file in nvim

### ISSUE THREAD

**Issue by nghiatd27** [iamcco/coc-angular#27]
**Describe the _bug**_
An error in angular template file look like this
"[ng] [E] Property binding rxLet not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".
I am using  @rx-angular/template
**To Reproduce**
1. Open a angular template file in nvim, that contain rxLet Directive
2. See the error
Where did I go wrong?
Notes: I open it template in Webstorm. It work fine

** versions
vim version: NVIM v0.5.0-dev
node version: v14.15.4
coc.nvim version: 0.0.80-6e5a2aaeb5
coc-angular: 11.1.3

**Expected behavior**
None of error will be show.

**Screenshots**
- A part of my Angular module, `LetModule` go here. my template is of a component of this module
![image](https://user-images.githubusercontent.com/38320790/106772774-eb9a6080-6672-11eb-8fae-9f8131312568.png)
- The entire error
![image](https://user-images.githubusercontent.com/38320790/106773366-8eeb7580-6673-11eb-9d4f-59c6719a335b.png)

```
```

**Comment by iamcco** [comment]
The diagnostics is from angularls, you can report here https://github.com/angular/vscode-ng-language-service
