### ISSUE TITLE
Incorrect syntax highlighting in html template

### ISSUE THREAD

**Issue by EnglederLucas** [iamcco/coc-angular#29]
**Describe the bug**
I am not getting the correct syntax highlighting on html template files. Non-standard-html elements are colored.

**To Reproduce**
1. Install Plugin
  Plug 'iamcco/coc-angular', {'do': 'yarn install --frozen-lockfile'} or
  Plug 'iamcco/coc-angular', {'do': 'yarn install --frozen-lockfile && yarn build'} (tried both)
2. Open angular (in my case) ionic html file

I also tried disabling coc-html with no success.

**Expected behavior**
I expected the correct syntax highlighting on custom elements

**Screenshots**
![image](https://user-images.githubusercontent.com/26169816/108593703-9ac67f80-7375-11eb-8110-590ab0125688.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64
Log: No logs

```
```

**Comment by iamcco** [comment]
No syntax highlight support by this extension.
