### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by ankitpal1029** [iamcco/coc-angular#30]
Hey i recently started learning angular and installed this via coc , it keeps throwing this error that the server crashed and it won't restart for no apparent reason .
Can someone help me out in this regard?
I am running 
NVIM v0.4.4
Angular: 11.2.6

![image](https://user-images.githubusercontent.com/49815751/111904852-ea7c9180-8a6e-11eb-886a-4bd7f6df2a67.png)

**Comment by iamcco** [comment]
Please test with latest version.

**Comment by ankitpal1029** [comment]
The latest version seems to be working without any issues. 
Thanks a lot for creating this plugin it's really helping me out a lot.
