### ISSUE TITLE
coc-angular seem just work with newest angular versions

### ISSUE THREAD

**Issue by kyoz** [iamcco/coc-angular#4]
I'v tried coc-angular in my new Angular project (version 8.0.0) and it work great.

But when i tried it in some old project with angular 5, 6. It doesn't trigger any completion candidates.

Could you give a try on it.

**Comment by iamcco** [comment]
Not work with angular 5/6 and have a look at https://github.com/angular/vscode-ng-language-service/issues/312

**Comment by iamcco** [comment]
Update to latest version
