### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Rofer11607** [iamcco/coc-angular#49]
**Describe the bug**

**To Reproduce**
start vim with coc-angular installed

**Expected behavior**
it should not crash

**Screenshots**
![Screen Shot 2022-03-02 at 4 38 42 PM](https://user-images.githubusercontent.com/55964540/156454084-8934d9b7-84c3-4376-8850-deebeef1b391.png)

**Desktop (please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/55964540/156454149-6d5230cf-4010-47ff-92f2-4ee155488d4f.png)

Log:

```
```

**Comment by Rofer11607** [comment]
Never mind, this happens if it is not installed. Is there a way to install globally?

**Comment by traitran44** [comment]
What did you do to fix this issue? After running `:CocInstall coc-angular`, I encountered the exact same issue on M1 MacOS Monterey

**Comment by Rofer11607** [comment]
This uses @angular/language-service, you have to install it in the project that you are using the plugin. Just do:
```
npm i @angular/language-service
```
In the project in question and it should work. My question to the devs is, how can we make this work on the global installation of the @angular/language-service package so that you don't have to do this in every angular project?

**Comment by traitran44** [comment]
> This uses @angular/language-service, you have to install it in the project that you are using the plugin. Just do:
> 
> ```
> npm i @angular/language-service
> ```
> 
> In the project in question and it should work. My question to the devs is, how can we make this work on the global installation of the @angular/language-service package so that you don't have to do this in every angular project?

This fixed the issue, thanks a lot. I think this should be added to home page README.

**Comment by iamcco** [comment]
It should work if `@angular/language-service` does not install in your project. Please test latest version.
