### ISSUE TITLE
Support Language features in inline templates

### ISSUE THREAD

**Issue by joeveiga** [iamcco/coc-angular#50]
**Describe the bug**

`vscode-ng-language-service` supports language service features (highlight, autocomplete, emmet, etc.) for **inline** angular templates as well as external templates:
 
https://github.com/angular/vscode-ng-language-service/commit/7a0e8616ad5270791ccd98c34192b79f86afaf76
https://github.com/angular/vscode-ng-language-service/commit/72ee5c71c90f454f554fc2d2d54805fb75d3cf7d

Is this something `coc-angular` can support?

**Screenshots**

![image](https://user-images.githubusercontent.com/19226858/157886927-c5fd0787-c438-481a-9377-03e738d4ef6f.png)

**Comment by iamcco** [comment]
`coc-angular` does not support syntax highlight for inline template, but LSP features ( autocomplete, hover document, goto definition, etc. ) should support.

**Comment by joeveiga** [comment]
@iamcco I see, thank you!
