### ISSUE TITLE
Angular 14 breaks coc-angular

### ISSUE THREAD

**Issue by fcojavierdomenech** [iamcco/coc-angular#62]
**Describe the bug**
Incompatibility with angular 14

**To Reproduce**
Use any coc-angular option withing an Angular 14, it won't work

I fixed it editing this plugin's `package.json` file and changing the angular language-server to 14:
```
....
"dependencies": {
    "v12_language_service": "file:v12_language_service",
    "@angular/language-server": "14",
    "typescript": "~4.6.2"
  }
```

**Comment by blasco** [comment]
Same situation for me, it doesn't seem to be working for angular 14

**Comment by msbatarce** [comment]
@fcojavierdomenech man,you saved me a lot of time with this small fix. Thank you
